In [8]:
import torch

t1 = torch.tensor([1,2])
t2 = torch.tensor([[3],[4]])

print('t1 shape :', t1.shape)
print('t2 shape :', t2.shape)

t1 shape : torch.Size([2])
t2 shape : torch.Size([2, 1])


In [7]:
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)

tensor([[4, 5],
        [5, 6]])
tensor([[-2, -1],
        [-3, -2]])
tensor([[3, 6],
        [4, 8]])


In [11]:
t2.matmul(t1)

RuntimeError: size mismatch, got input (2), mat (2x1), vec (2)

In [14]:
print(t1.add(t2))
print(t1.su


tensor([[4, 5],
        [5, 6]])
tensor([1, 2])
